### ISSUE TITLE
Could not find a version that satisfies the requirement jaxlib==0.1.48

### ISSUE THREAD

**Issue by kierad** [XanderJC/scalable-birl#9]
Hello, thank you for sharing this code.

When I run `pip install -e .` I see this error:
```
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.48 (from sbirl) (from versions: 0.1.72, 0.1.73, 0.1.74, 0.1.75, 0.1.76, 0.3.0, 0.3.2, 0.3.5, 0.3.7, 0.3.10, 0.3.14, 0.3.15, 0.3.20, 0.3.22, 0.3.24, 0.3.25, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7)
ERROR: No matching distribution found for jaxlib==0.1.48
```

I've tried updating `setup.py` to specify `jaxlib==0.1.72` and then run `python -c 'from sbirl import avril'` from  the `scalable-birl` directory, where I see this import error:

``` 
(avril) kierad@xxx scalable-birl % python -c 'from sbirl import avril'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kierad/Documents/GitHub/scalable-birl/sbirl/__init__.py", line 1, in <module>
    from .models import avril
  File "/Users/kierad/Documents/GitHub/scalable-birl/sbirl/models.py", line 1, in <module>
    import jax.numpy as np
  File "/Users/kierad/.virtualenvs/avril3/lib/python3.9/site-packages/jax/__init__.py", line 17, in <module>
    from .api import (
  File "/Users/kierad/.virtualenvs/avril3/lib/python3.9/site-packages/jax/api.py", line 38, in <module>
    from . import core
  File "/Users/kierad/.virtualenvs/avril3/lib/python3.9/site-packages/jax/core.py", line 31, in <module>
    from . import dtypes
  File "/Users/kierad/.virtualenvs/avril3/lib/python3.9/site-packages/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "/Users/kierad/.virtualenvs/avril3/lib/python3.9/site-packages/jax/lib/__init__.py", line 54, in <module>
    from jaxlib import pytree
ImportError: cannot import name 'pytree' from 'jaxlib' (/Users/kierad/.virtualenvs/avril3/lib/python3.9/site-packages/jaxlib/__init__.py)
(avril) kierad@xxx scalable-birl % python --version
Python 3.6.15
```

How can I fix this? I'm very keen to try out the model. Thank you.

**Comment by Czzz99111** [comment]
same problem
